spring:
  datasource:
    url: ENC(3tEJsW68wLmy8yIfSpUt11kz8IV3BF7RWnBexibhm25KE6LDechiMbn0kwzfuKuabIzC2+ssJTTxx32rQiy2Yjff5j3eHZuO)
    username: ENC(Z+kCoiiTU28oexg5wmaj/g==)
    password: ENC(RlzzorPTl/dnKbUpwlJTmRLWfKm7D+4H)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
      mode: always

logging:
  level:
    root: info
    com.hcs: debug
    org.hibernate.type: trace
    org.springframework.jdbc.core: trace
